# Generated by Django 2.2 on 2020-12-21 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roscon',
            name='año',
            field=models.SmallIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
