# Generated by Django 2.2 on 2020-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201221_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roscon',
            name='anno',
            field=models.SmallIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='tiporoscon',
            name='tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
